# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\software\ui_xml\ui_config_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigWidget(object):
    def setupUi(self, ConfigWidget):
        ConfigWidget.setObjectName("ConfigWidget")
        ConfigWidget.resize(510, 407)
        self.gridLayout = QtWidgets.QGridLayout(ConfigWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ConfigWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.animal_list = QtWidgets.QListWidget(ConfigWidget)
        self.animal_list.setObjectName("animal_list")
        self.horizontalLayout_2.addWidget(self.animal_list)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.animal_entry = QtWidgets.QLineEdit(ConfigWidget)
        self.animal_entry.setObjectName("animal_entry")
        self.verticalLayout.addWidget(self.animal_entry)
        self.animal_add = QtWidgets.QPushButton(ConfigWidget)
        self.animal_add.setObjectName("animal_add")
        self.verticalLayout.addWidget(self.animal_add)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.animal_del = QtWidgets.QPushButton(ConfigWidget)
        self.animal_del.setObjectName("animal_del")
        self.verticalLayout.addWidget(self.animal_del)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fruit_list = QtWidgets.QListWidget(ConfigWidget)
        self.fruit_list.setObjectName("fruit_list")
        self.horizontalLayout.addWidget(self.fruit_list)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.fruit_entry = QtWidgets.QLineEdit(ConfigWidget)
        self.fruit_entry.setObjectName("fruit_entry")
        self.verticalLayout_2.addWidget(self.fruit_entry)
        self.fruit_add = QtWidgets.QPushButton(ConfigWidget)
        self.fruit_add.setObjectName("fruit_add")
        self.verticalLayout_2.addWidget(self.fruit_add)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem7)
        self.fruit_del = QtWidgets.QPushButton(ConfigWidget)
        self.fruit_del.setObjectName("fruit_del")
        self.verticalLayout_2.addWidget(self.fruit_del)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ConfigWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)

        self.retranslateUi(ConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(ConfigWidget)

    def retranslateUi(self, ConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        ConfigWidget.setWindowTitle(_translate("ConfigWidget", "ConfigWidget"))
        self.label.setText(_translate("ConfigWidget", "Fruits"))
        self.animal_entry.setPlaceholderText(_translate("ConfigWidget", "animal"))
        self.animal_add.setText(_translate("ConfigWidget", "Add"))
        self.animal_del.setText(_translate("ConfigWidget", "Delete"))
        self.fruit_entry.setPlaceholderText(_translate("ConfigWidget", "fruit"))
        self.fruit_add.setText(_translate("ConfigWidget", "Add"))
        self.fruit_del.setText(_translate("ConfigWidget", "Delete"))
        self.label_2.setText(_translate("ConfigWidget", "Animals"))
